#modify by zhanghf;ov2688 is the ov2680b
obj-$(CONFIG_VIDEO_OV2680) += ov2680.o
obj-$(CONFIG_VIDEO_OV2688) += ov2688.o
#modify by zhanghf
#ov8858_driver-objs := ov8858.o dw9714.o vcm.o
#obj-$(CONFIG_VIDEO_OV8858)     += ov8858_driver.o

ccflags-y += -Werror
